apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus
    app.kubernetes.io/part-of: test-application
  name: devfile-sample-code-with-quarkus
spec:
  selector:
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus
status:
  loadBalancer: {}
